//
//  RecapShareView.swift
//  Scoor
//
//  공유 가능한 리캡 카드 — 라이브 프리뷰와 내보낸 이미지가 같은 뷰를 쓴다(단일 소스).
//  - RecapData: 카드가 그리는 값.
//  - RecapCardView: 브랜드 카드(밝은/어두운 테마 모두 결정론적으로 렌더).
//  - RecapStoryCanvas: 인스타 스토리(9:16) 풀블리드 배경 + 카드.
//

import SwiftUI

// MARK: - Data

struct RecapData: Equatable {
    var monthLine: String
    var averageText: String
    var topScoreText: String
    var topDateLabel: String
    var streakDays: Int
    /// 미니 히트맵 칸 강도(0...1, nil=기록 없음). 최대 14칸 사용.
    var intensities: [Double?]

    static let placeholder = RecapData(
        monthLine: "June\nSummary",
        averageText: "72 pts",
        topScoreText: "94",
        topDateLabel: "JUN 12",
        streakDays: 5,
        intensities: [0.8, 0.4, 0.9, 0.2, nil, 0.6, 0.7, 0.3, 1, 0.5, 0.9, nil, 0.6, 0.4]
    )
}

// MARK: - Card

/// 공유용 리캡 카드. `scheme`으로 라이트/다크 모두 결정론적 렌더.
struct RecapCardView: View {
    let data: RecapData
    var scheme: ColorScheme = .light

    private var cardBackground: Color {
        scheme == .dark ? Color(hex: "141417") : .white
    }
    private var primaryText: Color {
        scheme == .dark ? Color(hex: "F5F5F8") : Color(hex: "18181B")
    }
    private var subtleText: Color {
        scheme == .dark ? Color(hex: "8A8A93") : Color(red: 0.55, green: 0.58, blue: 0.62)
    }
    private var brand: Color { DesignTokens.primaryColor }

    var body: some View {
        VStack(spacing: 16) {
            ScoorLogo(size: 34, variant: scheme == .dark ? .white : .red)
                .padding(.bottom, 8)

            VStack(spacing: 4) {
                Text("MONTHLY REPORT")
                    .font(.system(size: 11, weight: .bold))
                    .foregroundStyle(brand.opacity(0.6))
                    .tracking(1.2)
                Text(data.monthLine)
                    .font(.system(size: 36, weight: .heavy))
                    .foregroundStyle(brand)
                    .multilineTextAlignment(.center)
                    .minimumScaleFactor(0.7)
            }

            LazyVGrid(columns: Array(repeating: GridItem(.flexible(), spacing: 6), count: 7), spacing: 6) {
                ForEach(Array(data.intensities.prefix(14).enumerated()), id: \.offset) { _, intensity in
                    RoundedRectangle(cornerRadius: 3)
                        .fill(brand.opacity(intensity.map { 0.15 + 0.85 * $0 } ?? 0.06))
                        .aspectRatio(1, contentMode: .fit)
                }
            }
            .padding(12)
            .background(brand.opacity(0.06))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))

            Text("Monthly score intensity")
                .font(.system(size: 10, weight: .medium))
                .foregroundStyle(subtleText)

            VStack(spacing: 0) {
                row(label: "Average", value: data.averageText)
                topDayRow
                row(label: "Streak", value: "\(data.streakDays) Days")
            }

            Text("Generated by Scoor for iOS")
                .font(.system(size: 10, weight: .medium))
                .foregroundStyle(subtleText)
        }
        .padding(24)
        .frame(maxWidth: 360)
        .background(cardBackground)
        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
        .overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).stroke(brand.opacity(0.08), lineWidth: 1))
        .shadow(color: .black.opacity(0.15), radius: 20, x: 0, y: 10)
    }

    private func row(label: String, value: String) -> some View {
        HStack {
            Text(label)
                .font(.system(size: 14, weight: .regular))
                .foregroundStyle(subtleText)
            Spacer()
            Text(value)
                .font(.system(size: 18, weight: .bold))
                .foregroundStyle(primaryText)
        }
        .padding(.vertical, 12)
        .overlay(alignment: .bottom) {
            Rectangle().fill(brand.opacity(0.1)).frame(height: 1)
        }
    }

    private var topDayRow: some View {
        HStack(alignment: .center) {
            Text("Top Day")
                .font(.system(size: 14, weight: .regular))
                .foregroundStyle(subtleText)
            Spacer()
            VStack(alignment: .trailing, spacing: 2) {
                Text(data.topScoreText)
                    .font(.system(size: 18, weight: .bold))
                    .foregroundStyle(primaryText)
                if !data.topDateLabel.isEmpty {
                    Text(data.topDateLabel)
                        .font(.system(size: 10, weight: .bold))
                        .foregroundStyle(brand)
                }
            }
        }
        .padding(.vertical, 12)
        .overlay(alignment: .bottom) {
            Rectangle().fill(brand.opacity(0.1)).frame(height: 1)
        }
    }
}

// MARK: - Story canvas (9:16 full-bleed for export)

/// 인스타 스토리용 풀블리드 캔버스. 포인트 360×640으로 디자인 → scale 3에서 1080×1920.
struct RecapStoryCanvas: View {
    let data: RecapData
    var scheme: ColorScheme = .light

    static let pointWidth: CGFloat = 360
    static let pointHeight: CGFloat = 640

    private var background: LinearGradient {
        let brand = DesignTokens.primaryColor
        if scheme == .dark {
            return LinearGradient(
                colors: [Color(hex: "1A0E0C"), Color(hex: "0A0A0B")],
                startPoint: .top, endPoint: .bottom
            )
        }
        return LinearGradient(
            colors: [brand.opacity(0.16), Color(hex: "F8F5F5")],
            startPoint: .top, endPoint: .bottom
        )
    }

    var body: some View {
        ZStack {
            background
            VStack(spacing: 20) {
                RecapCardView(data: data, scheme: scheme)
                    .frame(width: 300)
                Text("scoor.app")
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle((scheme == .dark ? Color.white : DesignTokens.primaryColor).opacity(0.7))
            }
            .padding(.horizontal, 24)
        }
        .frame(width: Self.pointWidth, height: Self.pointHeight)
    }
}

#Preview("Recap card – light") {
    RecapCardView(data: .placeholder, scheme: .light)
        .padding()
        .background(Color(hex: "F8F5F5"))
}

#Preview("Recap card – dark") {
    RecapCardView(data: .placeholder, scheme: .dark)
        .padding()
        .background(Color.black)
}

#Preview("Story canvas") {
    RecapStoryCanvas(data: .placeholder, scheme: .light)
}
